# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(935, 735)
        self.lbltitle = QtWidgets.QLabel(Dialog)
        self.lbltitle.setGeometry(QtCore.QRect(200, 20, 491, 111))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lbltitle.setFont(font)
        self.lbltitle.setAutoFillBackground(False)
        self.lbltitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltitle.setObjectName("lbltitle")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(170, 250, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.btncercacomm = QtWidgets.QPushButton(Dialog)
        self.btncercacomm.setGeometry(QtCore.QRect(600, 240, 161, 28))
        self.btncercacomm.setObjectName("btncercacomm")
        self.lblcercacomm = QtWidgets.QLabel(Dialog)
        self.lblcercacomm.setGeometry(QtCore.QRect(170, 220, 151, 16))
        self.lblcercacomm.setObjectName("lblcercacomm")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(170, 290, 591, 191))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.btnexit = QtWidgets.QPushButton(Dialog)
        self.btnexit.setGeometry(QtCore.QRect(752, 647, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnexit.setFont(font)
        self.btnexit.setObjectName("btnexit")

        self.retranslateUi(Dialog)
        self.btnexit.clicked.connect(Dialog.ExitDialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbltitle.setText(_translate("Dialog", "SW GESTIONE COMMESSE"))
        self.btncercacomm.setText(_translate("Dialog", "Cerca commessa"))
        self.lblcercacomm.setText(_translate("Dialog", "Seleziona commessa :"))
        self.btnexit.setText(_translate("Dialog", "Exit"))
